import { Tree } from '../models/models';

export const TreeData: Tree = [
  {
    label: 'ASSETS',
    id: 1,
    type: 'folder',
    path: 'ASSETS',
    branches: [],
  },
  {
    type: 'folder',
    label: 'LNDG',
    id: 2,
    path: 'LNDG',
    branches: [
      {
        label: 'LNDG_1200',
        id: 3,
        path: 'LNDG',
        type: 'file',
        branches: [],
      },
      {
        label: 'LNDG_0140',
        id: 4,
        path: 'LNDG',
        type: 'file',
        branches: [],
      },
      {
        label: 'LNDG_0160',
        id: 5,
        path: 'LNDG',
        type: 'file',
        branches: [],
      },
      {
        label: 'LNDG_0180',
        id: 6,
        path: 'LNDG',
        type: 'file',
        branches: [],
      },
      {
        label: 'LNDG_0200',
        id: 7,
        path: 'LNDG',
        type: 'file',
        branches: [],
      },
      {
        label: 'LNDG_0220',
        id: 8,
        path: 'LNDG',
        type: 'file',
        branches: [],
      },
    ],
  },
  {
    label: 'BARR',
    type: 'folder',
    id: 9,
    path: 'BARR',
    branches: [],
  },
  {
    label: 'BNGL',
    type: 'folder',
    path: 'BNGL',
    id: 10,
    branches: [],
  },
  {
    label: 'BNRK',
    type: 'folder',
    path: 'BNRK',
    id: 11,
    branches: [],
  },
  {
    label: 'BTTL',
    type: 'folder',
    path: 'BTTL',
    id: 12,
    branches: [],
  },
  {
    label: 'CLPS',
    type: 'folder',
    path: 'CLPS',
    id: 13,
    branches: [],
  },
  {
    label: 'ENGN',
    type: 'folder',
    path: 'ENGN',
    id: 14,
    branches: [],
  },
  {
    label: 'INTR',
    type: 'folder',
    path: 'INTR',
    id: 15,
    branches: [],
  },
  {
    label: 'LNDG',
    type: 'folder',
    path: 'LNDG',
    id: 16,
    branches: [],
  },
];
